import { DOCUMENT } from '@angular/common';
import { Injectable, inject, signal } from '@angular/core';

export type AppLanguage = 'en' | 'fr' | 'tn';

interface LanguageOption {
  code: AppLanguage;
  label: string;
  flagSrc: string;
  dir: 'ltr' | 'rtl';
  htmlLang: string;
}

const STORAGE_KEY = 'app-language';

const LANGUAGE_OPTIONS: LanguageOption[] = [
  { code: 'en', label: 'English', flagSrc: 'flags/us.svg', dir: 'ltr', htmlLang: 'en' },
  { code: 'fr', label: 'Francais', flagSrc: 'flags/fr.svg', dir: 'ltr', htmlLang: 'fr' },
  { code: 'tn', label: 'Tounsi', flagSrc: 'flags/tn.svg', dir: 'rtl', htmlLang: 'aeb-TN' }
];

const TEXTS: Record<AppLanguage, Record<string, string>> = {
  en: {
    'app.brand': 'Votica Template',
    'app.subtitle': 'Admin Dashboard',
    'footer.text': 'Copyright 2026 Votica Template Admin Dashboard. Built with Angular 21.',
    'nav.section.navigation': 'Navigation',
    'nav.section.ui': 'UI Element',
    'nav.section.forms': 'Forms',
    'nav.section.table': 'Table',
    'nav.section.auth': 'Auth',
    'nav.dashboard': 'Dashboard',
    'nav.analytics': 'Analytics',
    'nav.pageLayouts': 'Page Layouts',
    'nav.widget': 'Widget',
    'nav.user': 'User',
    'nav.basic': 'Basic',
    'nav.advance': 'Advance',
    'nav.animations': 'Animations',
    'nav.icons': 'Icons',
    'nav.forms': 'Forms',
    'nav.formsPlugins': 'Forms Plugins',
    'nav.textEditors': 'Text Editors',
    'nav.formLayouts': 'Form Layouts',
    'nav.fileUpload': 'File Upload',
    'nav.formValidation': 'Form Validation',
    'nav.imageCropper': 'Image Cropper',
    'nav.table': 'Table',
    'nav.dataTable': 'Data Table',
    'nav.tasks': 'Tasks',
    'nav.login': 'Login',
    'nav.register': 'Register',
    'nav.forgotPassword': 'Forgot Password',
    'nav.new': 'New',
    'header.searchPlaceholder': 'Search users, reports, orders...',
    'header.notifications': 'Notifications',
    'header.myProfile': 'My Profile',
    'header.accountSettings': 'Account Settings',
    'header.logout': 'Logout',
    'dashboard.title': 'Executive Dashboard',
    'dashboard.subtitle': 'Track revenue, users, growth, and operational activity in real time.',
    'dashboard.mrr': 'Monthly recurring revenue',
    'dashboard.revenueGrowth': 'Revenue Growth',
    'dashboard.newUsers': 'New Users',
    'dashboard.last7Days': 'Last 7 days',
    'dashboard.trafficSources': 'Traffic Sources',
    'dashboard.currentDistribution': 'Current distribution',
    'dashboard.recentActivity': 'Recent Activity',
    'dashboard.recentActivitySub': 'Latest product and billing events',
    'dashboard.recentOrders': 'Recent Orders',
    'dashboard.recentOrdersSub': 'Most recent order updates',
    'dashboard.recentUsers': 'Recent Users',
    'dashboard.recentUsersSub': 'New users added to the platform',
    'source.organic': 'Organic Search',
    'source.paid': 'Paid Ads',
    'source.social': 'Social',
    'source.direct': 'Direct',
    'users.title': 'User Management',
    'users.subtitle': 'Manage account roles, status, and lifecycle actions.',
    'users.listView': 'List View',
    'users.cardView': 'Card View',
    'users.addUser': 'Add User',
    'users.allUsers': 'All Users',
    'users.allUsersSub': 'Sorted, searchable, and paginated user list',
    'users.searchList': 'Search by name, email, role...',
    'users.searchCard': 'Search card view users...',
    'users.allRoles': 'All Roles',
    'users.allStatuses': 'All Statuses',
    'users.active': 'Active',
    'users.inactive': 'Inactive',
    'users.reset': 'Reset',
    'users.totalUsers': 'Total Users',
    'users.edit': 'Edit',
    'users.delete': 'Delete',
    'users.noMatch': 'No users match the current filters.',
    'users.deleteUser': 'Delete User',
    'users.keepUser': 'Keep User',
    'analytics.title': 'Analytics Insights',
    'analytics.subtitle': 'Advanced performance view with growth indicators and KPI tracking.',
    'analytics.trafficPerformance': 'Traffic Performance',
    'analytics.sessionsConversions': 'Sessions and conversions',
    'analytics.performanceScorecard': 'Performance Scorecard',
    'analytics.coreHealth': 'Core health indicators',
    'analytics.trafficStats': 'Traffic Stats',
    'analytics.sourceContribution': 'Source contribution',
    'analytics.monthlyComparison': 'Monthly Comparison',
    'analytics.yearComparison': 'Current year vs previous year',
    'table.search': 'Search...',
    'table.noResults': 'No results found.',
    'table.previous': 'Previous',
    'table.next': 'Next',
    'table.page': 'Page',
    'table.of': 'of',
    'table.name': 'Name',
    'table.email': 'Email',
    'table.role': 'Role',
    'table.status': 'Status',
    'table.actions': 'Actions',
    'table.orderId': 'Order ID',
    'table.customer': 'Customer',
    'table.amount': 'Amount',
    'table.date': 'Date',
    'status.active': 'Active',
    'status.inactive': 'Inactive',
    'status.processing': 'Processing',
    'status.completed': 'Completed',
    'status.cancelled': 'Cancelled',
    'auth.login.title': 'Welcome back',
    'auth.login.subtitle': 'Sign in to your Votica dashboard account.',
    'auth.email': 'Email address',
    'auth.password': 'Password',
    'auth.login.button': 'Login',
    'auth.forgot': 'Forgot password?',
    'auth.needAccount': 'Need an account?',
    'auth.register.link': 'Register',
    'auth.register.title': 'Create account',
    'auth.register.subtitle': 'Start managing your Votica SaaS operations.',
    'auth.fullName': 'Full name',
    'auth.register.button': 'Register',
    'auth.haveAccount': 'Already have an account?',
    'auth.login.link': 'Login',
    'auth.forgot.title': 'Forgot password',
    'auth.forgot.subtitle': 'We will email a reset link to your inbox.',
    'auth.sendReset': 'Send reset link',
    'auth.backTo': 'Back to',
    'ui.widget.title': 'Widget',
    'ui.widget.subtitle': 'UI components like cards, counters, and stats boxes.',
    'ui.basic.title': 'Basic',
    'ui.basic.subtitle': 'Basic UI elements: buttons, typography, colors, alerts, badges.',
    'ui.basic.buttonsBadges': 'Buttons and Badges',
    'ui.basic.typographyAlerts': 'Typography and Alerts',
    'ui.basic.primary': 'Primary',
    'ui.basic.ghost': 'Ghost',
    'ui.basic.danger': 'Danger',
    'ui.basic.headingExample': 'Heading Example',
    'ui.basic.typographyText': 'Consistent typography scale for premium dashboards.',
    'ui.basic.alert': 'This is a sample alert block for system notices.',
    'ui.advance.title': 'Advance',
    'ui.advance.subtitle': 'Advanced UI elements: modals, accordions, tabs, and dropdowns.',
    'ui.advance.library': 'Advanced Components Library',
    'ui.anim.title': 'Animations',
    'ui.anim.subtitle': 'Prebuilt animations: fade, slide, bounce, and hover effects.',
    'ui.anim.preview': 'Preview-ready motion preset',
    'ui.icons.title': 'Icons',
    'ui.icons.subtitle': 'Icon library: search, select, and copy icons for your UI.',
    'ui.icons.copied': 'Copied',
    'forms.basic.title': 'Forms',
    'forms.basic.subtitle': 'Basic form templates: inputs, checkboxes, radio buttons, and text areas.',
    'forms.basic.template': 'Profile Form Template',
    'forms.basic.fullName': 'Full Name',
    'forms.basic.email': 'Email',
    'forms.basic.role': 'Role',
    'forms.basic.bio': 'Bio',
    'forms.basic.status': 'Status',
    'forms.basic.updates': 'Receive weekly product updates',
    'forms.basic.cancel': 'Cancel',
    'forms.basic.save': 'Save Changes',
    'forms.plugins.title': 'Forms Plugins',
    'forms.plugins.subtitle': 'Advanced form components: date picker, color picker, and select/tag inputs.',
    'forms.plugins.inputs': 'Plugin-Style Inputs',
    'forms.plugins.launchDate': 'Launch Date',
    'forms.plugins.themeColor': 'Theme Color',
    'forms.plugins.framework': 'Framework Select',
    'forms.plugins.addTag': 'Add Tag',
    'forms.plugins.typeAdd': 'Type then add',
    'forms.plugins.add': 'Add',
    'forms.editors.title': 'Text Editors',
    'forms.editors.subtitle': 'WYSIWYG and code-editor style areas for rich text and developer content.',
    'forms.editors.wysiwyg': 'WYSIWYG Editor (Demo)',
    'forms.editors.code': 'Code Editor (Demo)',
    'forms.layouts.title': 'Form Layouts',
    'forms.layouts.subtitle': 'Different arrangements: horizontal, vertical, and multi-step forms.',
    'forms.layouts.horizontal': 'Horizontal Layout',
    'forms.layouts.vertical': 'Vertical Layout',
    'forms.layouts.multi': 'Multi-Step Layout',
    'forms.layouts.name': 'Name',
    'forms.layouts.company': 'Company',
    'forms.layouts.website': 'Website',
    'forms.layouts.step': 'Step',
    'forms.layouts.accountSetup': 'Account setup',
    'forms.layouts.teamDetails': 'Team details',
    'forms.layouts.review': 'Review',
    'forms.layouts.previous': 'Previous',
    'forms.layouts.next': 'Next',
    'forms.upload.title': 'File Upload',
    'forms.upload.subtitle': 'Upload files/images with drag-drop and multiple file selection.',
    'forms.upload.zone': 'Upload Zone',
    'forms.upload.dragDrop': 'Drag and drop files here, or select manually.',
    'forms.upload.none': 'No files selected yet.',
    'forms.validation.title': 'Form Validation',
    'forms.validation.subtitle': 'Client-side and server-side validation examples with error handling.',
    'forms.validation.demo': 'Validation Demo',
    'forms.validation.invalidEmail': 'Please enter a valid email address.',
    'forms.validation.invalidPassword': 'Password must be at least 8 characters.',
    'forms.validation.submit': 'Validate Form',
    'forms.validation.serverEmailTaken': 'Server validation: this email is already registered.',
    'forms.cropper.title': 'Image Cropper',
    'forms.cropper.subtitle': 'Preview, rotate, and zoom controls before saving an image.',
    'forms.cropper.demo': 'Cropper Demo',
    'forms.cropper.zoom': 'Zoom',
    'forms.cropper.rotate': 'Rotate 90 deg',
    'forms.cropper.save': 'Save Cropped Image',
    'table.basic.title': 'Table',
    'table.basic.subtitle': 'Data tables for listing items with sorting, filtering, and pagination.',
    'table.basic.inventory': 'Inventory Listing',
    'table.basic.inventorySub': 'Search, sort, and paginate products',
    'table.basic.filter': 'Filter by SKU, product, category...',
    'table.sku': 'SKU',
    'table.product': 'Product',
    'table.category': 'Category',
    'table.stock': 'Stock',
    'table.data.title': 'Data Table',
    'table.data.subtitle': 'Sorting, filtering, pagination, inline edit, and export options.',
    'table.data.filterDeals': 'Filter deals...',
    'table.data.export': 'Export CSV',
    'table.data.dealId': 'Deal ID',
    'table.data.owner': 'Owner',
    'table.data.value': 'Value',
    'table.data.inlineEdit': 'Inline Edit',
    'table.data.save': 'Save',
    'table.data.prev': 'Prev',
    'table.data.next': 'Next',
    'pageLayouts.title': 'Page Layouts',
    'pageLayouts.subtitle': 'Prebuilt templates for different page types.',
    'pageLayouts.overview': 'Templates Overview',
    'pageLayouts.examples': 'Examples: login page, profile page, landing page',
    'pageLayouts.intro': 'Choose a layout, preview it, then customize spacing, colors, and sections.',
    'pageLayouts.preview': 'Preview',
    'pageLayouts.customize': 'Customize',
    'pageLayouts.controls': 'Customization Controls',
    'pageLayouts.controlsSub': 'Ability to preview and customize layouts',
    'tasks.title': 'Team Tasks',
    'tasks.subtitle': 'Operational overview',
    'settings.title': 'Account Settings',
    'settings.subtitle': 'Customize your workspace preferences',
    'settings.copy': 'Settings modules are ready for integration with real APIs.',
    'profile.title': 'My Profile',
    'profile.subtitle': 'Personal details and account snapshot',
    'profile.role': 'Product Director',
    'widget.activeSubs': 'Active Subscriptions',
    'widget.monthlyRevenue': 'Monthly Revenue',
    'widget.openTickets': 'Open Tickets',
    'widget.conversionRate': 'Conversion Rate',
    'advance.modal': 'Modal Variants',
    'advance.modalUsage': 'Delete confirmations, onboarding, detail view',
    'advance.accordion': 'Accordion Sets',
    'advance.accordionUsage': 'FAQ blocks and settings groups',
    'advance.tabs': 'Tabs',
    'advance.tabsUsage': 'Analytics filters and profile modules',
    'advance.dropdown': 'Dropdown Menus',
    'advance.dropdownUsage': 'Topbar profile and notifications',
    'anim.fadeIn': 'Fade In',
    'anim.slideUp': 'Slide Up',
    'anim.bounceHover': 'Bounce Hover',
    'anim.scaleReveal': 'Scale Reveal',
    'forms.editors.richTitle': 'Release Notes',
    'forms.editors.richBody': 'New dashboard widgets are now available with improved loading performance and updated analytics views.',
    'pageLayouts.card.loginName': 'Login Page Layout',
    'pageLayouts.card.loginType': 'Authentication',
    'pageLayouts.card.loginDesc': 'Minimal auth-focused layout with centered form and brand section.',
    'pageLayouts.card.profileName': 'Profile Page Layout',
    'pageLayouts.card.profileType': 'User',
    'pageLayouts.card.profileDesc': 'Personal profile layout with avatar block, account details, and activity.',
    'pageLayouts.card.landingName': 'Landing Page Layout',
    'pageLayouts.card.landingType': 'Marketing',
    'pageLayouts.card.landingDesc': 'Conversion-oriented landing layout with hero, feature blocks, and CTA.',
    'pageLayouts.card.settingsName': 'Settings Page Layout',
    'pageLayouts.card.settingsType': 'System',
    'pageLayouts.card.settingsDesc': 'Structured settings layout for preferences, security, and notifications.',
    'pageLayouts.option.colors': 'Color Palette',
    'pageLayouts.option.colorsValue': 'Blue / Teal',
    'pageLayouts.option.typo': 'Typography Set',
    'pageLayouts.option.typoValue': 'Manrope + Space Grotesk',
    'pageLayouts.option.spacing': 'Spacing Scale',
    'pageLayouts.option.spacingValue': '8px baseline grid',
    'pageLayouts.option.layout': 'Layout Mode',
    'pageLayouts.option.layoutValue': 'Boxed / Full Width'
  },
  fr: {
    'app.brand': 'Modele Votica',
    'app.subtitle': 'Tableau de bord',
    'footer.text': 'Copyright 2026 Votica Template Admin Dashboard. Construit avec Angular 21.',
    'nav.section.navigation': 'Navigation',
    'nav.section.ui': 'Elements UI',
    'nav.section.forms': 'Formulaires',
    'nav.section.table': 'Tableaux',
    'nav.section.auth': 'Auth',
    'nav.dashboard': 'Tableau de bord',
    'nav.analytics': 'Analytique',
    'nav.pageLayouts': 'Mises en page',
    'nav.widget': 'Widget',
    'nav.user': 'Utilisateur',
    'nav.basic': 'Basique',
    'nav.advance': 'Avance',
    'nav.animations': 'Animations',
    'nav.icons': 'Icones',
    'nav.forms': 'Formulaires',
    'nav.formsPlugins': 'Plugins formulaires',
    'nav.textEditors': 'Editeurs de texte',
    'nav.formLayouts': 'Layouts formulaires',
    'nav.fileUpload': 'Televersement',
    'nav.formValidation': 'Validation formulaire',
    'nav.imageCropper': 'Rognage image',
    'nav.table': 'Table',
    'nav.dataTable': 'Data table',
    'nav.tasks': 'Taches',
    'nav.login': 'Connexion',
    'nav.register': 'Inscription',
    'nav.forgotPassword': 'Mot de passe oublie',
    'nav.new': 'Nouveau',
    'header.searchPlaceholder': 'Rechercher utilisateurs, rapports, commandes...',
    'header.notifications': 'Notifications',
    'header.myProfile': 'Mon profil',
    'header.accountSettings': 'Parametres du compte',
    'header.logout': 'Deconnexion',
    'dashboard.title': 'Tableau de bord executif',
    'dashboard.subtitle': 'Suivez revenus, utilisateurs, croissance et activite operationnelle en temps reel.',
    'dashboard.mrr': 'Revenu mensuel recurrent',
    'dashboard.revenueGrowth': 'Croissance des revenus',
    'dashboard.newUsers': 'Nouveaux utilisateurs',
    'dashboard.last7Days': '7 derniers jours',
    'dashboard.trafficSources': 'Sources de trafic',
    'dashboard.currentDistribution': 'Distribution actuelle',
    'dashboard.recentActivity': 'Activite recente',
    'dashboard.recentActivitySub': 'Derniers evenements produit et facturation',
    'dashboard.recentOrders': 'Commandes recentes',
    'dashboard.recentOrdersSub': 'Dernieres mises a jour commandes',
    'dashboard.recentUsers': 'Utilisateurs recents',
    'dashboard.recentUsersSub': 'Nouveaux utilisateurs ajoutes',
    'source.organic': 'Recherche organique',
    'source.paid': 'Publicites payantes',
    'source.social': 'Reseaux sociaux',
    'source.direct': 'Direct',
    'users.title': 'Gestion des utilisateurs',
    'users.subtitle': 'Gerez les roles, statuts et actions du cycle utilisateur.',
    'users.listView': 'Vue liste',
    'users.cardView': 'Vue cartes',
    'users.addUser': 'Ajouter utilisateur',
    'users.allUsers': 'Tous les utilisateurs',
    'users.allUsersSub': 'Liste triee, recherche et pagination',
    'users.searchList': 'Rechercher par nom, email, role...',
    'users.searchCard': 'Rechercher dans la vue cartes...',
    'users.allRoles': 'Tous les roles',
    'users.allStatuses': 'Tous les statuts',
    'users.active': 'Actif',
    'users.inactive': 'Inactif',
    'users.reset': 'Reinitialiser',
    'users.totalUsers': 'Total utilisateurs',
    'users.edit': 'Modifier',
    'users.delete': 'Supprimer',
    'users.noMatch': 'Aucun utilisateur ne correspond aux filtres.',
    'users.deleteUser': 'Supprimer utilisateur',
    'users.keepUser': 'Garder utilisateur',
    'analytics.title': 'Apercu analytique',
    'analytics.subtitle': 'Vue avancee des performances et indicateurs KPI.',
    'analytics.trafficPerformance': 'Performance trafic',
    'analytics.sessionsConversions': 'Sessions et conversions',
    'analytics.performanceScorecard': 'Score de performance',
    'analytics.coreHealth': 'Indicateurs de sante',
    'analytics.trafficStats': 'Statistiques trafic',
    'analytics.sourceContribution': 'Contribution des sources',
    'analytics.monthlyComparison': 'Comparaison mensuelle',
    'analytics.yearComparison': 'Annee courante vs precedente',
    'table.search': 'Rechercher...',
    'table.noResults': 'Aucun resultat.',
    'table.previous': 'Precedent',
    'table.next': 'Suivant',
    'table.page': 'Page',
    'table.of': 'sur',
    'table.name': 'Nom',
    'table.email': 'Email',
    'table.role': 'Role',
    'table.status': 'Statut',
    'table.actions': 'Actions',
    'table.orderId': 'ID commande',
    'table.customer': 'Client',
    'table.amount': 'Montant',
    'table.date': 'Date',
    'status.active': 'Actif',
    'status.inactive': 'Inactif',
    'status.processing': 'En cours',
    'status.completed': 'Termine',
    'status.cancelled': 'Annule',
    'auth.login.title': 'Bon retour',
    'auth.login.subtitle': 'Connectez-vous a votre tableau de bord Votica.',
    'auth.email': 'Adresse email',
    'auth.password': 'Mot de passe',
    'auth.login.button': 'Connexion',
    'auth.forgot': 'Mot de passe oublie ?',
    'auth.needAccount': 'Besoin dun compte ?',
    'auth.register.link': 'Inscription',
    'auth.register.title': 'Creer un compte',
    'auth.register.subtitle': 'Commencez a gerer vos operations SaaS.',
    'auth.fullName': 'Nom complet',
    'auth.register.button': 'Inscription',
    'auth.haveAccount': 'Vous avez deja un compte ?',
    'auth.login.link': 'Connexion',
    'auth.forgot.title': 'Mot de passe oublie',
    'auth.forgot.subtitle': 'Nous allons envoyer un lien de reinitialisation.',
    'auth.sendReset': 'Envoyer le lien',
    'auth.backTo': 'Retour a',
    'ui.widget.title': 'Widget',
    'ui.widget.subtitle': 'Composants UI: cartes, compteurs et boites de stats.',
    'ui.basic.title': 'Basique',
    'ui.basic.subtitle': 'Elements UI de base: boutons, typo, couleurs, alertes, badges.',
    'ui.basic.buttonsBadges': 'Boutons et badges',
    'ui.basic.typographyAlerts': 'Typographie et alertes',
    'ui.basic.primary': 'Primaire',
    'ui.basic.ghost': 'Ghost',
    'ui.basic.danger': 'Danger',
    'ui.basic.headingExample': 'Exemple de titre',
    'ui.basic.typographyText': 'Echelle typographique coherente pour dashboard premium.',
    'ui.basic.alert': 'Bloc dalerte exemple pour notifications systeme.',
    'ui.advance.title': 'Avance',
    'ui.advance.subtitle': 'Elements avances: modals, accordions, tabs et dropdowns.',
    'ui.advance.library': 'Bibliotheque de composants avances',
    'ui.anim.title': 'Animations',
    'ui.anim.subtitle': 'Animations pretes: fade, slide, bounce et hover effects.',
    'ui.anim.preview': 'Preset de mouvement pret a utiliser',
    'ui.icons.title': 'Icones',
    'ui.icons.subtitle': 'Bibliotheque dicones: chercher, selectionner et copier.',
    'ui.icons.copied': 'Copie',
    'forms.basic.title': 'Formulaires',
    'forms.basic.subtitle': 'Modeles de base: champs, checkbox, radio et textarea.',
    'forms.basic.template': 'Modele formulaire profil',
    'forms.basic.fullName': 'Nom complet',
    'forms.basic.email': 'Email',
    'forms.basic.role': 'Role',
    'forms.basic.bio': 'Bio',
    'forms.basic.status': 'Statut',
    'forms.basic.updates': 'Recevoir les mises a jour hebdomadaires',
    'forms.basic.cancel': 'Annuler',
    'forms.basic.save': 'Enregistrer',
    'forms.plugins.title': 'Plugins formulaires',
    'forms.plugins.subtitle': 'Composants avances: date, couleur, select et tags.',
    'forms.plugins.inputs': 'Champs style plugin',
    'forms.plugins.launchDate': 'Date de lancement',
    'forms.plugins.themeColor': 'Couleur theme',
    'forms.plugins.framework': 'Selection framework',
    'forms.plugins.addTag': 'Ajouter tag',
    'forms.plugins.typeAdd': 'Saisir puis ajouter',
    'forms.plugins.add': 'Ajouter',
    'forms.editors.title': 'Editeurs de texte',
    'forms.editors.subtitle': 'Zones WYSIWYG et code-editor pour contenu riche.',
    'forms.editors.wysiwyg': 'Editeur WYSIWYG (Demo)',
    'forms.editors.code': 'Editeur code (Demo)',
    'forms.layouts.title': 'Layouts formulaires',
    'forms.layouts.subtitle': 'Dispositions horizontale, verticale et multi-etapes.',
    'forms.layouts.horizontal': 'Layout horizontal',
    'forms.layouts.vertical': 'Layout vertical',
    'forms.layouts.multi': 'Layout multi-etapes',
    'forms.layouts.name': 'Nom',
    'forms.layouts.company': 'Entreprise',
    'forms.layouts.website': 'Site web',
    'forms.layouts.step': 'Etape',
    'forms.layouts.accountSetup': 'Configuration compte',
    'forms.layouts.teamDetails': 'Details equipe',
    'forms.layouts.review': 'Revision',
    'forms.layouts.previous': 'Precedent',
    'forms.layouts.next': 'Suivant',
    'forms.upload.title': 'Televersement',
    'forms.upload.subtitle': 'Envoyer des fichiers/images avec drag-drop et multi-selection.',
    'forms.upload.zone': 'Zone de televersement',
    'forms.upload.dragDrop': 'Glissez-deposez les fichiers ici, ou selection manuelle.',
    'forms.upload.none': 'Aucun fichier selectionne.',
    'forms.validation.title': 'Validation formulaire',
    'forms.validation.subtitle': 'Validation client et serveur avec gestion des erreurs.',
    'forms.validation.demo': 'Demo validation',
    'forms.validation.invalidEmail': 'Veuillez saisir une adresse email valide.',
    'forms.validation.invalidPassword': 'Le mot de passe doit contenir au moins 8 caracteres.',
    'forms.validation.submit': 'Valider formulaire',
    'forms.validation.serverEmailTaken': 'Validation serveur: cet email est deja utilise.',
    'forms.cropper.title': 'Rognage image',
    'forms.cropper.subtitle': 'Apercu, rotation et zoom avant sauvegarde.',
    'forms.cropper.demo': 'Demo cropper',
    'forms.cropper.zoom': 'Zoom',
    'forms.cropper.rotate': 'Tourner 90 deg',
    'forms.cropper.save': 'Enregistrer image rognee',
    'table.basic.title': 'Table',
    'table.basic.subtitle': 'Listes avec tri, filtre et pagination.',
    'table.basic.inventory': 'Inventaire produits',
    'table.basic.inventorySub': 'Rechercher, trier et paginer les produits',
    'table.basic.filter': 'Filtrer par SKU, produit, categorie...',
    'table.sku': 'SKU',
    'table.product': 'Produit',
    'table.category': 'Categorie',
    'table.stock': 'Stock',
    'table.data.title': 'Data table',
    'table.data.subtitle': 'Tri, filtre, pagination, edition inline et export.',
    'table.data.filterDeals': 'Filtrer les deals...',
    'table.data.export': 'Exporter CSV',
    'table.data.dealId': 'ID deal',
    'table.data.owner': 'Proprietaire',
    'table.data.value': 'Valeur',
    'table.data.inlineEdit': 'Edition inline',
    'table.data.save': 'Enregistrer',
    'table.data.prev': 'Prec',
    'table.data.next': 'Suiv',
    'pageLayouts.title': 'Mises en page',
    'pageLayouts.subtitle': 'Modeles predefinis pour differents types de pages.',
    'pageLayouts.overview': 'Apercu des modeles',
    'pageLayouts.examples': 'Exemples: login, profil, landing page',
    'pageLayouts.intro': 'Choisissez un layout, previsualisez, puis personnalisez.',
    'pageLayouts.preview': 'Apercu',
    'pageLayouts.customize': 'Personnaliser',
    'pageLayouts.controls': 'Controles de personnalisation',
    'pageLayouts.controlsSub': 'Possibilite de previsualiser et personnaliser',
    'tasks.title': 'Taches equipe',
    'tasks.subtitle': 'Vue operationnelle',
    'settings.title': 'Parametres du compte',
    'settings.subtitle': 'Personnalisez vos preferences workspace',
    'settings.copy': 'Les modules de parametres sont prets pour integration API.',
    'profile.title': 'Mon profil',
    'profile.subtitle': 'Details personnels et resume du compte',
    'profile.role': 'Directeur produit',
    'widget.activeSubs': 'Abonnements actifs',
    'widget.monthlyRevenue': 'Revenu mensuel',
    'widget.openTickets': 'Tickets ouverts',
    'widget.conversionRate': 'Taux de conversion',
    'advance.modal': 'Variantes modal',
    'advance.modalUsage': 'Confirmations suppression, onboarding, vue detail',
    'advance.accordion': 'Ensembles accordion',
    'advance.accordionUsage': 'Blocs FAQ et groupes de parametres',
    'advance.tabs': 'Onglets',
    'advance.tabsUsage': 'Filtres analytiques et modules profil',
    'advance.dropdown': 'Menus dropdown',
    'advance.dropdownUsage': 'Profil topbar et notifications',
    'anim.fadeIn': 'Fondu',
    'anim.slideUp': 'Glisser vers le haut',
    'anim.bounceHover': 'Rebond hover',
    'anim.scaleReveal': 'Revelation echelle',
    'forms.editors.richTitle': 'Notes de version',
    'forms.editors.richBody': 'De nouveaux widgets dashboard sont disponibles avec de meilleures performances de chargement.',
    'pageLayouts.card.loginName': 'Layout page connexion',
    'pageLayouts.card.loginType': 'Authentification',
    'pageLayouts.card.loginDesc': 'Layout minimal centre sur auth avec formulaire centre.',
    'pageLayouts.card.profileName': 'Layout page profil',
    'pageLayouts.card.profileType': 'Utilisateur',
    'pageLayouts.card.profileDesc': 'Layout profil avec avatar, details compte et activite.',
    'pageLayouts.card.landingName': 'Layout landing page',
    'pageLayouts.card.landingType': 'Marketing',
    'pageLayouts.card.landingDesc': 'Layout orientee conversion avec hero, features et CTA.',
    'pageLayouts.card.settingsName': 'Layout page parametres',
    'pageLayouts.card.settingsType': 'Systeme',
    'pageLayouts.card.settingsDesc': 'Layout structure pour preferences, securite et notifications.',
    'pageLayouts.option.colors': 'Palette de couleurs',
    'pageLayouts.option.colorsValue': 'Bleu / Turquoise',
    'pageLayouts.option.typo': 'Jeu typographique',
    'pageLayouts.option.typoValue': 'Manrope + Space Grotesk',
    'pageLayouts.option.spacing': 'Echelle despacement',
    'pageLayouts.option.spacingValue': 'Grille 8px',
    'pageLayouts.option.layout': 'Mode layout',
    'pageLayouts.option.layoutValue': 'Boxed / Largeur complete'
  },
  tn: {
    'app.brand': 'Votica',
    'app.subtitle': 'Dashboard Admin',
    'footer.text': 'جميع الحقوق محفوظة 2026 Votica Template Admin Dashboard. مبني بـ Angular 21.',
    'nav.section.navigation': 'التنقل',
    'nav.section.ui': 'عناصر الواجهة',
    'nav.section.forms': 'الفورمات',
    'nav.section.table': 'الجداول',
    'nav.section.auth': 'تسجيل',
    'nav.dashboard': 'الداشبور',
    'nav.analytics': 'الاحصائيات',
    'nav.pageLayouts': 'تصاميم الصفحات',
    'nav.widget': 'ويدجت',
    'nav.user': 'المستخدمين',
    'nav.basic': 'اساسيات',
    'nav.advance': 'متقدم',
    'nav.animations': 'انميشن',
    'nav.icons': 'ايقونات',
    'nav.forms': 'فورمات',
    'nav.formsPlugins': 'بلوجينات الفورم',
    'nav.textEditors': 'محررات النص',
    'nav.formLayouts': 'تنظيم الفورم',
    'nav.fileUpload': 'رفع ملفات',
    'nav.formValidation': 'تحقق الفورم',
    'nav.imageCropper': 'قص الصور',
    'nav.table': 'جدول',
    'nav.dataTable': 'داتا جدول',
    'nav.tasks': 'تاسكات',
    'nav.login': 'دخول',
    'nav.register': 'تسجيل',
    'nav.forgotPassword': 'نسيت الباسورد',
    'nav.new': 'جديد',
    'header.searchPlaceholder': 'قلّب على المستخدمين، التقارير، والطلبات...',
    'header.notifications': 'الاشعارات',
    'header.myProfile': 'بروفيلي',
    'header.accountSettings': 'اعدادات الحساب',
    'header.logout': 'خروج',
    'dashboard.title': 'Dashboard التنفيذي',
    'dashboard.subtitle': 'تابع الدخل، المستخدمين، النمو والنشاط اليومي في الوقت الحقيقي.',
    'dashboard.mrr': 'الدخل الشهري المتكرر',
    'dashboard.revenueGrowth': 'نمو الدخل',
    'dashboard.newUsers': 'مستخدمين جداد',
    'dashboard.last7Days': 'اخر 7 ايام',
    'dashboard.trafficSources': 'مصادر الزيارات',
    'dashboard.currentDistribution': 'التوزيع الحالي',
    'dashboard.recentActivity': 'اخر النشاطات',
    'dashboard.recentActivitySub': 'اخر الاحداث متاع المنتج والفوترة',
    'dashboard.recentOrders': 'اخر الطلبات',
    'dashboard.recentOrdersSub': 'اخر تحديثات الطلبات',
    'dashboard.recentUsers': 'مستخدمين جداد',
    'dashboard.recentUsersSub': 'اخر المستخدمين اللي تزادو',
    'source.organic': 'بحث طبيعي',
    'source.paid': 'اشهار ممول',
    'source.social': 'سوشيال',
    'source.direct': 'ديركت',
    'users.title': 'ادارة المستخدمين',
    'users.subtitle': 'بدل الادوار، الحالة، وكل عمليات المستخدمين.',
    'users.listView': 'عرض جدول',
    'users.cardView': 'عرض كروت',
    'users.addUser': 'زيد مستخدم',
    'users.allUsers': 'كل المستخدمين',
    'users.allUsersSub': 'ترتيب، بحث، وتقسيم صفحات',
    'users.searchList': 'قلّب بالاسم، الايميل، ولا الدور...',
    'users.searchCard': 'قلّب في عرض الكروت...',
    'users.allRoles': 'كل الادوار',
    'users.allStatuses': 'كل الحالات',
    'users.active': 'نشط',
    'users.inactive': 'موش نشط',
    'users.reset': 'اعادة',
    'users.totalUsers': 'عدد المستخدمين',
    'users.edit': 'تعديل',
    'users.delete': 'حذف',
    'users.noMatch': 'ما ثماش مستخدمين يوافقو الفلترة.',
    'users.deleteUser': 'حذف المستخدم',
    'users.keepUser': 'خليه',
    'analytics.title': 'تحليل الاداء',
    'analytics.subtitle': 'نظرة متقدمة على الاداء و KPI.',
    'analytics.trafficPerformance': 'اداء الزيارات',
    'analytics.sessionsConversions': 'الجلسات والتحويلات',
    'analytics.performanceScorecard': 'بطاقة الاداء',
    'analytics.coreHealth': 'مؤشرات الصحة',
    'analytics.trafficStats': 'احصائيات الزيارات',
    'analytics.sourceContribution': 'مساهمة المصادر',
    'analytics.monthlyComparison': 'مقارنة شهرية',
    'analytics.yearComparison': 'السنة الحالية مقابل اللي قبلها',
    'table.search': 'بحث...',
    'table.noResults': 'ما ثماش نتائج.',
    'table.previous': 'السابق',
    'table.next': 'التالي',
    'table.page': 'صفحة',
    'table.of': 'من',
    'table.name': 'الاسم',
    'table.email': 'الايميل',
    'table.role': 'الدور',
    'table.status': 'الحالة',
    'table.actions': 'عمليات',
    'table.orderId': 'رقم الطلب',
    'table.customer': 'الحريف',
    'table.amount': 'المبلغ',
    'table.date': 'التاريخ',
    'status.active': 'نشط',
    'status.inactive': 'موش نشط',
    'status.processing': 'قيد المعالجة',
    'status.completed': 'مكمل',
    'status.cancelled': 'ملغي',
    'auth.login.title': 'مرحبا بيك',
    'auth.login.subtitle': 'ادخل لحسابك في Dashboard Votica.',
    'auth.email': 'البريد الالكتروني',
    'auth.password': 'كلمة المرور',
    'auth.login.button': 'دخول',
    'auth.forgot': 'نسيت كلمة المرور؟',
    'auth.needAccount': 'ما عندكش حساب؟',
    'auth.register.link': 'تسجيل',
    'auth.register.title': 'اعمل حساب جديد',
    'auth.register.subtitle': 'ابدأ سيّر عمليات SaaS متاعك.',
    'auth.fullName': 'الاسم الكامل',
    'auth.register.button': 'تسجيل',
    'auth.haveAccount': 'عندك حساب قبل؟',
    'auth.login.link': 'دخول',
    'auth.forgot.title': 'نسيت كلمة المرور',
    'auth.forgot.subtitle': 'باش نبعتولك رابط استرجاع على الايميل.',
    'auth.sendReset': 'ابعث رابط الاسترجاع',
    'auth.backTo': 'ارجع لـ',
    'ui.widget.title': 'ويدجت',
    'ui.widget.subtitle': 'عناصر واجهة كيما الكروت، الكاونترات، وصناديق الاحصائيات.',
    'ui.basic.title': 'اساسيات',
    'ui.basic.subtitle': 'عناصر UI اساسية: زراير، خطوط، الوان، تنبيهات، badges.',
    'ui.basic.buttonsBadges': 'الزراير والبادجات',
    'ui.basic.typographyAlerts': 'الخطوط والتنبيهات',
    'ui.basic.primary': 'اساسي',
    'ui.basic.ghost': 'شفاف',
    'ui.basic.danger': 'خطر',
    'ui.basic.headingExample': 'مثال عنوان',
    'ui.basic.typographyText': 'تنظيم خطوط ثابت لدashboard احترافي.',
    'ui.basic.alert': 'هذا مثال alert للتنبيهات متاع السيستام.',
    'ui.advance.title': 'متقدم',
    'ui.advance.subtitle': 'عناصر متقدمة: modal, accordion, tabs, dropdowns.',
    'ui.advance.library': 'مكتبة العناصر المتقدمة',
    'ui.anim.title': 'انميشن',
    'ui.anim.subtitle': 'انميشنات جاهزة: fade, slide, bounce و hover.',
    'ui.anim.preview': 'preset motion جاهز',
    'ui.icons.title': 'ايقونات',
    'ui.icons.subtitle': 'مكتبة ايقونات: لوج، اختار، وانسخ.',
    'ui.icons.copied': 'تنسخ',
    'forms.basic.title': 'فورمات',
    'forms.basic.subtitle': 'قوالب اساسية: input, checkbox, radio, textarea.',
    'forms.basic.template': 'قالب فورم البروفايل',
    'forms.basic.fullName': 'الاسم الكامل',
    'forms.basic.email': 'الايميل',
    'forms.basic.role': 'الدور',
    'forms.basic.bio': 'نبذة',
    'forms.basic.status': 'الحالة',
    'forms.basic.updates': 'وصلني تحديثات اسبوعية',
    'forms.basic.cancel': 'الغاء',
    'forms.basic.save': 'حفظ التغييرات',
    'forms.plugins.title': 'بلوجينات الفورم',
    'forms.plugins.subtitle': 'مكونات متقدمة: تاريخ، لون، اختيار، tags.',
    'forms.plugins.inputs': 'حقول ستايل plugin',
    'forms.plugins.launchDate': 'تاريخ الانطلاق',
    'forms.plugins.themeColor': 'لون الثيم',
    'forms.plugins.framework': 'اختيار framework',
    'forms.plugins.addTag': 'زيد tag',
    'forms.plugins.typeAdd': 'اكتب وبعد زيد',
    'forms.plugins.add': 'زيد',
    'forms.editors.title': 'محررات النص',
    'forms.editors.subtitle': 'مساحات WYSIWYG و code editor للنصوص.',
    'forms.editors.wysiwyg': 'محرر WYSIWYG (Demo)',
    'forms.editors.code': 'محرر Code (Demo)',
    'forms.layouts.title': 'تنظيم الفورم',
    'forms.layouts.subtitle': 'تنظيم افقي، عمودي، ومراحل.',
    'forms.layouts.horizontal': 'تنظيم افقي',
    'forms.layouts.vertical': 'تنظيم عمودي',
    'forms.layouts.multi': 'تنظيم متعدد المراحل',
    'forms.layouts.name': 'الاسم',
    'forms.layouts.company': 'الشركة',
    'forms.layouts.website': 'الموقع',
    'forms.layouts.step': 'مرحلة',
    'forms.layouts.accountSetup': 'اعداد الحساب',
    'forms.layouts.teamDetails': 'تفاصيل الفريق',
    'forms.layouts.review': 'مراجعة',
    'forms.layouts.previous': 'السابق',
    'forms.layouts.next': 'التالي',
    'forms.upload.title': 'رفع الملفات',
    'forms.upload.subtitle': 'رفع ملفات/صور بالdrag-drop واختيار متعدد.',
    'forms.upload.zone': 'منطقة الرفع',
    'forms.upload.dragDrop': 'جر وحط الملفات هنا، ولا اختار يدوي.',
    'forms.upload.none': 'ما ثماش ملفات مختارة.',
    'forms.validation.title': 'تحقق الفورم',
    'forms.validation.subtitle': 'تحقق جهة المستخدم والسيرفر مع اخطاء واضحة.',
    'forms.validation.demo': 'ديمو التحقق',
    'forms.validation.invalidEmail': 'دخل ايميل صحيح.',
    'forms.validation.invalidPassword': 'كلمة المرور لازم 8 حروف على الاقل.',
    'forms.validation.submit': 'تحقق من الفورم',
    'forms.validation.serverEmailTaken': 'تحقق السيرفر: الايميل هذا مسجل قبل.',
    'forms.cropper.title': 'قص الصور',
    'forms.cropper.subtitle': 'معاينة، تدوير، وزوم قبل الحفظ.',
    'forms.cropper.demo': 'ديمو القص',
    'forms.cropper.zoom': 'زوم',
    'forms.cropper.rotate': 'دوّر 90 درجة',
    'forms.cropper.save': 'احفظ الصورة المقصوصة',
    'table.basic.title': 'جدول',
    'table.basic.subtitle': 'جداول فيها ترتيب، فلترة، وتقسيم صفحات.',
    'table.basic.inventory': 'قائمة المخزون',
    'table.basic.inventorySub': 'قلّب، رتّب، وقسم المنتجات',
    'table.basic.filter': 'فلتر ب SKU، المنتج، الصنف...',
    'table.sku': 'SKU',
    'table.product': 'المنتج',
    'table.category': 'الصنف',
    'table.stock': 'المخزون',
    'table.data.title': 'داتا جدول',
    'table.data.subtitle': 'ترتيب، فلترة، pagination، تعديل مباشر وتصدير.',
    'table.data.filterDeals': 'فلتر الصفقات...',
    'table.data.export': 'صدّر CSV',
    'table.data.dealId': 'رقم الصفقة',
    'table.data.owner': 'المسؤول',
    'table.data.value': 'القيمة',
    'table.data.inlineEdit': 'تعديل مباشر',
    'table.data.save': 'حفظ',
    'table.data.prev': 'قبل',
    'table.data.next': 'بعد',
    'pageLayouts.title': 'تصاميم الصفحات',
    'pageLayouts.subtitle': 'قوالب جاهزة لانواع مختلفة من الصفحات.',
    'pageLayouts.overview': 'نظرة على القوالب',
    'pageLayouts.examples': 'امثلة: login، profile، landing page',
    'pageLayouts.intro': 'اختار layout، شوف المعاينة، وبعد عدّل المسافات والالوان.',
    'pageLayouts.preview': 'معاينة',
    'pageLayouts.customize': 'تخصيص',
    'pageLayouts.controls': 'اعدادات التخصيص',
    'pageLayouts.controlsSub': 'تنجم تعاين وتخصص كل layout',
    'tasks.title': 'تاسكات الفريق',
    'tasks.subtitle': 'نظرة تشغيلية',
    'settings.title': 'اعدادات الحساب',
    'settings.subtitle': 'خصص اعدادات workspace متاعك',
    'settings.copy': 'موديولات الاعدادات جاهزة لربطها مع API حقيقية.',
    'profile.title': 'بروفيلي',
    'profile.subtitle': 'المعطيات الشخصية وملخص الحساب',
    'profile.role': 'مدير المنتج',
    'widget.activeSubs': 'اشتراكات نشيطة',
    'widget.monthlyRevenue': 'الدخل الشهري',
    'widget.openTickets': 'تذاكر مفتوحة',
    'widget.conversionRate': 'نسبة التحويل',
    'advance.modal': 'انواع Modal',
    'advance.modalUsage': 'تاكيدات الحذف، onboarding، وعرض التفاصيل',
    'advance.accordion': 'مجموعات Accordion',
    'advance.accordionUsage': 'بلوكات FAQ ومجموعات الاعدادات',
    'advance.tabs': 'Tabs',
    'advance.tabsUsage': 'فلاتر الاحصائيات وموديولات البروفايل',
    'advance.dropdown': 'Dropdown Menus',
    'advance.dropdownUsage': 'بروفايل topbar والاشعارات',
    'anim.fadeIn': 'Fade In',
    'anim.slideUp': 'Slide Up',
    'anim.bounceHover': 'Bounce Hover',
    'anim.scaleReveal': 'Scale Reveal',
    'forms.editors.richTitle': 'ملاحظات التحديث',
    'forms.editors.richBody': 'زادت widgets جديدة في الداشبور مع تحسين في سرعة التحميل وعرض التحليلات.',
    'pageLayouts.card.loginName': 'Layout صفحة الدخول',
    'pageLayouts.card.loginType': 'تسجيل',
    'pageLayouts.card.loginDesc': 'Layout بسيط موجه للدخول مع فورم في الوسط وبراند واضح.',
    'pageLayouts.card.profileName': 'Layout صفحة البروفايل',
    'pageLayouts.card.profileType': 'مستخدم',
    'pageLayouts.card.profileDesc': 'Layout بروفايل فيه avatar وتفاصيل الحساب والنشاط.',
    'pageLayouts.card.landingName': 'Layout الصفحة الرئيسية',
    'pageLayouts.card.landingType': 'تسويق',
    'pageLayouts.card.landingDesc': 'Layout موجه للتحويل فيه hero وميزات و CTA.',
    'pageLayouts.card.settingsName': 'Layout صفحة الاعدادات',
    'pageLayouts.card.settingsType': 'سيستم',
    'pageLayouts.card.settingsDesc': 'Layout منظم للتفضيلات، الامان، والاشعارات.',
    'pageLayouts.option.colors': 'لوحة الالوان',
    'pageLayouts.option.colorsValue': 'ازرق / تركواز',
    'pageLayouts.option.typo': 'مجموعة الخطوط',
    'pageLayouts.option.typoValue': 'Manrope + Space Grotesk',
    'pageLayouts.option.spacing': 'مقياس المسافات',
    'pageLayouts.option.spacingValue': 'شبكة 8px',
    'pageLayouts.option.layout': 'نمط Layout',
    'pageLayouts.option.layoutValue': 'Boxed / Full Width'
  }
};

@Injectable({
  providedIn: 'root'
})
export class LanguageService {
  private readonly document = inject(DOCUMENT);
  readonly options = LANGUAGE_OPTIONS;
  readonly current = signal<AppLanguage>('en');

  constructor() {
    this.initLanguage();
  }

  setLanguage(code: AppLanguage): void {
    const option = this.options.find((item) => item.code === code);
    if (!option) {
      return;
    }

    this.current.set(code);
    this.document.documentElement.setAttribute('lang', option.htmlLang);
    this.document.documentElement.setAttribute('dir', option.dir);
    localStorage.setItem(STORAGE_KEY, code);
  }

  t(key: string): string {
    const map = TEXTS[this.current()];
    return map[key] ?? TEXTS.en[key] ?? key;
  }

  private initLanguage(): void {
    const stored = localStorage.getItem(STORAGE_KEY) as AppLanguage | null;
    if (stored === 'en' || stored === 'fr' || stored === 'tn') {
      this.setLanguage(stored);
      return;
    }
    this.setLanguage('en');
  }
}

